import { ArrowRight, BadgePercent, ChevronRight, PackageSearch, ShoppingBag, Sparkles, Star, Store, Truck } from "lucide-react";
import type { ReactNode } from "react";
import { Link } from "react-router-dom";
import PageContainer from "@/components/layout/PageContainer";
import ProductGrid from "@/components/marketplace/ProductGrid";
import ProductCard from "@/components/marketplace/ProductCard";
import CategoryGrid from "@/components/marketplace/CategoryGrid";
import BusinessCard from "@/components/marketplace/BusinessCard";
import Button from "@/components/ui/Button";
import { useMarketplaceBusinesses, useMarketplaceCategories, useMarketplaceProducts } from "@/hooks/useMarketplace";

export default function Home() {
  const { products, loading: productsLoading } = useMarketplaceProducts({ limit: 100 });
  const { categories, loading: categoriesLoading } = useMarketplaceCategories();
  const { businesses, loading: businessesLoading } = useMarketplaceBusinesses();
  const deals = products.filter((p) => p.compareAtPrice != null && p.compareAtPrice > p.price).slice(0, 5);
  const featured = products.filter((p) => p.featured).slice(0, 10);
  const latest = products.slice(0, 10);
  const stores = businesses.filter((b) => b.productCount > 0).slice(0, 6);

  return <div className="min-h-screen bg-slate-50">
    <section className="bg-[#082A63] text-white"><PageContainer className="py-10 sm:py-14"><div className="grid gap-5 lg:grid-cols-[1.5fr_.7fr]"><div className="rounded-2xl bg-white/10 p-7 backdrop-blur sm:p-10"><span className="inline-flex items-center gap-2 rounded-full bg-white/10 px-3 py-1 text-xs font-semibold"><Sparkles className="h-3.5 w-3.5 text-[#F4B400]"/> IyanjuWorld marketplace</span><h1 className="mt-5 text-4xl font-black leading-tight sm:text-5xl">Discover products from real businesses.</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-blue-50 sm:text-base">Every product shown here comes from an active business owner on IyanjuWorld. Browse, compare and shop with confidence.</p><div className="mt-7 flex flex-wrap gap-3"><Link to="/products"><Button className="bg-[#F4B400] text-[#082A63] hover:bg-[#ffc928]">Shop products <ArrowRight className="h-4 w-4"/></Button></Link><Link to="/businesses"><Button variant="outline" className="border-white/40 bg-white/10 text-white hover:bg-white hover:text-[#082A63]">Explore stores</Button></Link></div></div><div className="grid grid-cols-2 gap-4 lg:grid-cols-1"><Link to="/products?deals=true" className="rounded-xl bg-[#fff3d2] p-5 text-[#082A63]"><BadgePercent className="h-8 w-8"/><p className="mt-4 text-xs font-bold uppercase tracking-wide">Real seller deals</p><h2 className="mt-1 text-xl font-black">See current offers</h2></Link><Link to="/businesses" className="rounded-xl bg-[#e8f1ff] p-5 text-[#082A63]"><Store className="h-8 w-8"/><p className="mt-4 text-xs font-bold uppercase tracking-wide">Business stores</p><h2 className="mt-1 text-xl font-black">Shop by seller</h2></Link></div></div></PageContainer></section>
    <main className="mx-auto max-w-[1440px] px-4 pb-16 sm:px-6 lg:px-8">
      <section className="py-8"><SectionHeader title="Shop by Category" href="/explore"/><CategoryGrid categories={categories.map(c => ({ id:c.id, name:c.name, slug:c.slug, imageUrl:c.imageUrl, productCount:c.productCount }))} columns={6} className="lg:grid-cols-8" emptyState={<Empty text={categoriesLoading ? "Loading categories…" : "Categories will appear here when they are added."}/>}/></section>
      {deals.length > 0 && <section className="rounded-xl bg-[#082A63] p-5 text-white sm:p-7"><SectionHeader dark title="Flash Deals" href="/products?deals=true"/><ProductGrid products={deals.map(toCard)} columns={5} emptyState={<Empty text="No current deals."/>}/></section>}
      <section className="py-10"> <SectionHeader title="Featured Products" subtitle="Products actually published by marketplace businesses" href="/products"/> <ProductGrid loading={productsLoading} products={featured.map(toCard)} columns={5} emptyState={<Empty icon text="No featured products have been published yet."/>}/></section>
      <section className="py-2"> <SectionHeader title="Latest Products" subtitle="Recently published products from active businesses" href="/products"/> <ProductGrid loading={productsLoading} products={latest.map(toCard)} columns={5} emptyState={<Empty icon text="No products are available yet. Business owners can publish products from their dashboard."/>}/></section>
      <section className="mt-10 rounded-xl border border-slate-200 bg-white p-5 sm:p-7"><SectionHeader title="Business Stores" subtitle="Active businesses with products available to shop" href="/businesses"/><div className="grid gap-4 md:grid-cols-3">{businessesLoading ? <div className="col-span-full py-8 text-center text-sm text-slate-500">Loading stores…</div> : stores.map(b => <BusinessCard key={b.id} business={{ id:b.id, name:b.name, slug:b.slug, description:b.description, logoUrl:b.logoUrl, coverUrl:b.coverUrl, city:b.city, state:b.state, verified:b.verified, open:b.open, productCount:b.productCount }}/>)}</div>{!businessesLoading && stores.length === 0 && <Empty icon text="No active business stores with published products yet."/>}</section>
      <section className="py-10"><div className="grid gap-4 md:grid-cols-3"><Feature icon={<ShoppingBag/>} title="Real marketplace inventory" text="Only database products that meet marketplace visibility rules are displayed."/><Feature icon={<Truck/>} title="Shop active businesses" text="Store information comes from the business records that power IyanjuWorld."/><Feature icon={<Star/>} title="No fake listings" text="If sellers have not published products yet, the marketplace stays empty instead of showing demo data."/></div></section>
    </main>
  </div>;
}
function toCard(p:any){return {id:p.id,name:p.name,slug:p.slug,businessName:p.businessName,businessSlug:p.businessSlug,price:p.price,compareAtPrice:p.compareAtPrice,imageUrl:p.imageUrl,categoryName:p.categoryName,stock:p.stock,available:p.available,featured:p.featured};}
function SectionHeader({title,subtitle,href,dark=false}:{title:string;subtitle?:string;href?:string;dark?:boolean}){return <div className="mb-5 flex items-end justify-between gap-4"><div><h2 className={`text-2xl font-black tracking-tight sm:text-3xl ${dark?'text-white':'text-slate-950'}`}>{title}</h2>{subtitle&&<p className={dark?'mt-1 text-sm text-blue-100':'mt-1 text-sm text-slate-500'}>{subtitle}</p>}</div>{href&&<Link to={href} className={`flex shrink-0 items-center gap-1 text-sm font-bold ${dark?'text-white hover:text-[#F4B400]':'text-[#082A63]'}`}>See all <ChevronRight className="h-4 w-4"/></Link>}</div>}
function Empty({text,icon=false}:{text:string;icon?:boolean}){return <div className="col-span-full rounded-xl border border-dashed border-slate-200 bg-white px-6 py-10 text-center text-sm text-slate-500">{icon&&<PackageSearch className="mx-auto mb-3 h-8 w-8 text-slate-300"/>}{text}</div>}
function Feature({icon,title,text}:{icon:ReactNode;title:string;text:string}){return <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex h-11 w-11 items-center justify-center rounded-full bg-[#eef3fb] text-[#082A63]">{icon}</div><h3 className="mt-4 font-bold text-slate-900">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{text}</p></div>}
