import { useEffect, useState } from "react";
import { Search as SearchIcon } from "lucide-react";
import { useSearchParams, Link } from "react-router-dom";
import PageContainer from "@/components/layout/PageContainer";
import ProductGrid from "@/components/marketplace/ProductGrid";
import BusinessCard from "@/components/marketplace/BusinessCard";
import { useMarketplaceProducts, useMarketplaceBusinesses } from "@/hooks/useMarketplace";
export default function Search(){const [params,setParams]=useSearchParams();const [q,setQ]=useState(params.get("q")??"");const {products,loading:pl}=useMarketplaceProducts({search:q,limit:100});const {businesses,loading:bl}=useMarketplaceBusinesses();const matches=businesses.filter(b=>!q||`${b.name} ${b.description??""} ${b.city??""} ${b.state??""}`.toLowerCase().includes(q.toLowerCase()));useEffect(()=>{const t=setTimeout(()=>{if(q) setParams({q});else setParams({});},250);return()=>clearTimeout(t)},[q,setParams]);return <PageContainer><div className="space-y-8 pb-16"><section className="rounded-2xl border bg-white p-6"><h1 className="text-3xl font-black">Search IyanjuWorld</h1><div className="relative mt-5 max-w-3xl"><SearchIcon className="absolute left-3 top-1/2 h-5 w-5 -translate-y-1/2 text-slate-400"/><input autoFocus value={q} onChange={e=>setQ(e.target.value)} placeholder="Search products or stores…" className="h-12 w-full rounded-xl border border-slate-200 bg-slate-50 pl-11 pr-4 outline-none focus:bg-white"/></div></section><section><div className="mb-4 flex items-center justify-between"><h2 className="text-2xl font-black">Products</h2><Link to="/products" className="text-sm font-bold text-[#082A63]">Browse all</Link></div><ProductGrid loading={pl} products={products.map(toCard)} columns={5} emptyState={<div className="rounded-xl border border-dashed bg-white p-10 text-center text-sm text-slate-500">No published products match your search.</div>}/></section><section><h2 className="mb-4 text-2xl font-black">Stores</h2>{bl?<div className="py-8 text-center text-sm text-slate-500">Loading stores…</div>:<div className="grid gap-4 md:grid-cols-2">{matches.filter(b=>b.productCount>0).slice(0,6).map(b=><BusinessCard key={b.id} business={{id:b.id,name:b.name,slug:b.slug,description:b.description,logoUrl:b.logoUrl,coverUrl:b.coverUrl,city:b.city,state:b.state,verified:b.verified,open:b.open,productCount:b.productCount}}/>)}</div>}</section></div></PageContainer>}
function toCard(p:any){return {id:p.id,name:p.name,slug:p.slug,businessName:p.businessName,businessSlug:p.businessSlug,price:p.price,compareAtPrice:p.compareAtPrice,imageUrl:p.imageUrl,categoryName:p.categoryName,stock:p.stock,available:p.available,featured:p.featured};}
